---
name: Release
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/inko-lang/inko:main
    steps:
      - run: microdnf install --quiet --assumeyes tar git
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        id: test
        with:
          path: '~/.local/share/inko/packages'
          key: deps-${{ hashFiles('inko.pkg') }}
      - run: inko --version
      - run: inko test

  build:
    runs-on: ubuntu-latest
    needs:
       - test
    container:
      image: ghcr.io/inko-lang/idoc:latest
    steps:
      - name: Install dependencies
        run: microdnf install --quiet --assumeyes tar git
      - uses: actions/checkout@v4
      - name: Build documentation
        run: idoc
      - name: Upload documentation
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/idoc/public

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4

